# Welcome to Jekyll!

# Website settings
title: Selnord Consultants
tittledesc: exclusive agent & distributor
titlelink: Vinmar International
titleurl: http://vinmar.com
description: HDPE, LLDPE, LLDPE, PVC, PET, PS and other polymers distribution
keywords: CYNPOL, HDPE, LLDPE, LLDPE, PVC, PET, PS, polymers, СИНПОЛ, ПВХ, ПВД, ПНД, линейный полиэтилен, полимеры из США
baseurl:  #/Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://selnord.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: GitHub  # Be used at blog posts' author.
  first_name: Selnord  # Be used at index page about me section.
  last_name: Consultants  # Be used at index page about me section.
  avatar: /static/assets/img/landing/logoselnord_site.jpg  # upload your avatar at directory and edit it.
  github_username:  # Leave blank if you don't have now
  linkedin_id:  # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: team@selnord.com  # Leave blank if you don't have now
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now
  # service icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  service_icon1:
    - name:
    - name:
  service_icon2:
    - name:
    - name:

  desc: "Selnord Consultants is a  marketing, distribution and project development company that brings value to the producers and users of petrochemical products through tailored business solutions."  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: #jalpc
  public_key: #tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  UA-9458297-1 # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
